" Load pathogen vim plugin for easy plugin managing support
runtime bundle/vim-pathogen/autoload/pathogen.vim

syntax on
if has('gui_running')
    set background=light
else
    set background=dark
endif
colorscheme solarized

filetype plugin indent on
