" Load pathogen vim plugin for easy plugin managing support
execute pathogen#infect()

syntax on
if has('gui_running')
	set background=light
else
	set background=dark
endif
colorscheme solarized

filetype plugin indent on
